//! Compile the vendored tree-sitter-rhai C grammar into a static library.
//!
//! The `parser.c` file is generated by `tree-sitter generate` from
//! `grammar.js` upstream — we vendor the generated C, not the JS, so we
//! don't need a Node toolchain to build. The grammar is self-contained
//! (it includes `tree_sitter/parser.h`), so we only need `cc` and an
//! include path.

fn main() {
    let grammar_dir = std::path::Path::new("grammar");
    let parser_c = grammar_dir.join("parser.c");

    println!("cargo:rerun-if-changed={}", parser_c.display());
    println!("cargo:rerun-if-changed=grammar/tree_sitter/parser.h");
    println!("cargo:rerun-if-changed=grammar/tree_sitter/alloc.h");
    println!("cargo:rerun-if-changed=grammar/tree_sitter/array.h");

    let mut build = cc::Build::new();
    build
        .include(grammar_dir)
        .file(&parser_c)
        // Generated tree-sitter parsers trigger a number of benign
        // warnings (unused parameters, sign comparisons in generated
        // tables). We silence them to keep build output clean — the C
        // is generated, not maintained, so warnings have no signal.
        .flag_if_supported("-Wno-unused-parameter")
        .flag_if_supported("-Wno-unused-but-set-variable")
        .flag_if_supported("-Wno-trigraphs")
        .warnings(false);

    build.compile("tree-sitter-rhai");
}
