#!/usr/bin/env bash
#
# Regenerate editor/tree-sitter-gluon/queries/highlights.scm from the
# live Gluon engine registration surface.
#
# Why: the tree-sitter query list of "DSL builtin function names" is
# the same list the `gluon-lsp` binary exposes at runtime. Rather than
# hand-maintain it in two places (drift-prone) we derive it from a
# single oracle: `gluon internal dump-dsl`, which runs the same
# `engine::register_all` code path the real build uses and returns
# every Rhai signature via `rhai::Engine::gen_fn_signatures`.
#
# Workflow: whenever you add or rename a `register_fn` in
# crates/gluon-core/src/engine/builders/, run this script, review the
# diff, and commit the regenerated `highlights.scm` alongside the
# engine change.
#
# Requirements:
#   - cargo + rustc (to build the gluon binary the first time)
#   - jq         (to parse the JSON output)
#
# This script is idempotent: running it twice against the same engine
# produces a byte-identical file. Useful for CI checks — see the
# trailing `--check` mode.

set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
queries_dir="$repo_root/editor/tree-sitter-gluon/queries"
target="$queries_dir/highlights.scm"

check_only=false
if [[ "${1-}" == "--check" ]]; then
  check_only=true
fi

mkdir -p "$queries_dir"

# Drop through to `--manifest-path` so the script works from any cwd.
# The `-q` silences cargo's "Compiling …" chatter so our stdout
# capture is clean JSON.
dsl_json=$(cargo run -q \
  --manifest-path "$repo_root/Cargo.toml" \
  --bin gluon -- \
  internal dump-dsl)

# Extract the bare function name from every "name(params) -> Ret"
# entry, dedupe, sort deterministically. `split("(") | .[0]` handles
# every shape Rhai's metadata emits — there's always at least one `(`.
names=$(printf '%s' "$dsl_json" | jq -r '
  .signatures[]
  | split("(")
  | .[0]
  | sub("^\\s+|\\s+$"; "")
  | select(length > 0)
' | sort -u)

if [[ -z "$names" ]]; then
  echo "regen-dsl-queries: dump-dsl returned no signatures — aborting" >&2
  exit 1
fi

# Build the new file in a buffer so we can compare it atomically
# against the current contents (for --check).
new_content=$(
  cat <<'HEADER'
; This file is generated by scripts/regen-dsl-queries.sh.
; Do not edit by hand — rerun the script instead.
;
; Source of truth: crates/gluon-core/src/engine/builders/
; Oracle: `gluon internal dump-dsl`
;
; Layer this on top of tree-sitter-rhai's base highlights. Every
; identifier that matches a Gluon DSL entry point or builder method
; is captured as @function.builtin so the editor colors them as
; builtins instead of plain identifiers.
HEADER
  echo
  echo "((identifier) @function.builtin"
  echo " (#any-of? @function.builtin"
  while IFS= read -r name; do
    printf '   "%s"\n' "$name"
  done <<< "$names"
  echo " ))"
)

if [[ "$check_only" == true ]]; then
  if [[ -f "$target" ]] && diff -q <(printf '%s\n' "$new_content") "$target" > /dev/null; then
    echo "regen-dsl-queries: $target is up to date"
    exit 0
  fi
  echo "regen-dsl-queries: $target is STALE — rerun without --check" >&2
  diff <(printf '%s\n' "$new_content") "$target" || true
  exit 1
fi

printf '%s\n' "$new_content" > "$target"
echo "regen-dsl-queries: wrote $target ($(printf '%s\n' "$names" | wc -l | tr -d ' ') names)"
